export const ENV_KEYS = {
    DATABASE_URL: 'DATABASE_URL',
    JWT_SECRET: 'JWT_SECRET',
    JWT_EXPIRES_IN_SECONDS: 'JWT_EXPIRES_IN_SECONDS',
} as const;

export const DEFAULT_JWT_EXPIRES_IN_SECONDS = 28_800;